# (c) 2017 KAI OS TECHNOLOGIES (HONG KONG) LIMITED All rights reserved. This
# file or any portion thereof may not be reproduced or used in any manner
# whatsoever without the express written permission of KAI OS TECHNOLOGIES
# (HONG KONG) LIMITED. KaiOS is the trademark of KAI OS TECHNOLOGIES (HONG KONG)
# LIMITED or its affiliate company and may be registered in some jurisdictions.
# All other trademarks are the property of their respective owners.

variables:
  GIT_DEPTH: 1
  DEFAULT_DOCKER_IMAGE: "${CI_REGISTRY}/re/kaios-build/next/desktop:latest"
  GIT_CLONE_PATH: ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/gecko

.global_setup: &global_setup
  - echo -e "machine ${CI_SERVER_HOST}\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
  - git config --global url."${CI_SERVER_URL}/".insteadOf "git@${CI_SERVER_HOST}:"
  - '[ "$(cat ${HOME}/.mozbuild/ver)" = "2" ] || curl https://packages.preprod.kaiostech.com/ndk/v2/mozbuild.tar.bz2 | tar -C ${HOME}/ -xj'

default:
  image: $DEFAULT_DOCKER_IMAGE
  tags:
    - gecko-dev
  before_script:
    - *global_setup

stages:
  - lint
  - build

lint:all:
  stage: lint
  tags:
    - gecko-lint
  variables:
    DEFAULT_DOCKER_IMAGE: "${CI_REGISTRY}/re/kaios-build/next/daily:latest"
    # force the runner not to initialize the repository
    GIT_STRATEGY: none
  script:
    - apt-get install jq -yy
    - |
      depth=$(curl -s \
        -H "Private-Token: ${GITLAB_API_KEY}" \
        "${CI_API_V4_URL}/projects/${CI_MERGE_REQUEST_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/commits" \
        | jq length)
    - |
      git clone ${CI_MERGE_REQUEST_SOURCE_PROJECT_URL}.git \
        -b ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} \
        --depth $((depth+1)) \
      ${GIT_CLONE_PATH}
    - |
      pushd ${GIT_CLONE_PATH}
      ./mach create-mach-environment
    - |
      ./check-format.sh --against "HEAD~${depth}" -v
      popd
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /skip-lint/

build:desktop:
  variables:
    MOZ_OBJDIR: 'objdir-desktop-gecko'
    MOZCONFIG: 'mozconfig-b2g-desktop'
  stage: build
  script:
    - ./mach build
    - ./mach package
  artifacts:
    expire_in: 1 week
    paths:
      - "objdir-desktop-gecko/dist/b2g-*"
  only:
    - merge_requests

build:emulator:
  before_script:
    - *global_setup
    - git clone --depth 1 git@git.kaiostech.com:KaiOS/dummy/emulator-10.git > /dev/null 2>&1
  variables:
    DEFAULT_DOCKER_IMAGE: "${CI_REGISTRY}/re/kaios-build/next/daily:latest"
    GONK_PATH: "${CI_PROJECT_DIR}/emulator-10"
    GECKO_OBJDIR: "${CI_PROJECT_DIR}/objdir-emulator-gecko"
    GONK_PRODUCT_NAME: generic_x86_64
    PLATFORM_VERSION: 29
    TARGET_ARCH: x86_64
    TARGET_ARCH_VARIANT: x86_64
    TARGET_CPU_VARIANT: generic
    BINSUFFIX: 64
    B2G_DEBUG: 1
  stage: build
  script:
    - ./build-b2g.sh
    - ./build-b2g.sh package
  only:
    - merge_requests

build:arm:
  before_script:
    - *global_setup
    - git clone --depth 1 git@git.kaiostech.com:KaiOS/koost.git -b next > /dev/null 2>&1
    - git clone --depth 1 git@git.kaiostech.com:KaiOS/dummy/gonk-q.git > /dev/null 2>&1
  variables:
    DEFAULT_DOCKER_IMAGE: "${CI_REGISTRY}/re/kaios-build/next/daily:latest"
    GONK_PATH: "${CI_PROJECT_DIR}/gonk-q"
    GECKO_OBJDIR: "${CI_PROJECT_DIR}/objdir-arm-gecko"
    GONK_PRODUCT_NAME: msm8937_32go
    GET_FRAMEBUFFER_FORMAT_FROM_HWC: 1
    PLATFORM_VERSION: 29
    TARGET_ARCH: arm
    TARGET_ARCH_VARIANT: armv8-a
    TARGET_CPU_VARIANT: cortex-a53
    ANDROID_NDK: '~/.mozbuild/android-ndk-r20b-canary'
    PRODUCT_MANUFACTURER: QUALCOMM
  stage: build
  script:
    - ./build-b2g.sh
    - ./build-b2g.sh package
  only:
    - merge_requests
  artifacts:
    expire_in: 2 week
    paths:
      - "objdir-arm-gecko/dist/b2g-*"
      - "push-b2g.sh"
